"""
Add proper India Choropleth Map to MASTER_file.ipynb
Uses plotly for interactive choropleth with India state boundaries
"""
import json
from pathlib import Path

notebook_path = Path(r'c:\Users\anish\Desktop\UIDAI_HACKATHON\notebooks\MASTER_file.ipynb')

# Load existing notebook
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Choropleth map cells
choropleth_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "\n",
            "## 8.3 🗺️ India Choropleth Map: IFI Risk by State\n",
            "\n",
            "**A geographic visualization showing Identity Freshness Index across all Indian states and UTs.**\n",
            "\n",
            "This is the most impactful visual for understanding where Aadhaar data staleness risk is concentrated geographically."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# INDIA CHOROPLETH MAP - IFI BY STATE\n",
            "# ============================================\n",
            "\n",
            "import plotly.express as px\n",
            "import plotly.graph_objects as go\n",
            "import json\n",
            "import urllib.request\n",
            "\n",
            "print(\"=\"*70)\n",
            "print(\"🗺️ GENERATING INDIA CHOROPLETH MAP\")\n",
            "print(\"=\"*70)\n",
            "\n",
            "# Load India GeoJSON from public source\n",
            "india_geojson_url = 'https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson'\n",
            "\n",
            "try:\n",
            "    with urllib.request.urlopen(india_geojson_url) as url:\n",
            "        india_geojson = json.loads(url.read().decode())\n",
            "    print(\"✓ India GeoJSON loaded successfully\")\n",
            "except:\n",
            "    print(\"⚠️ Could not load GeoJSON from URL, using fallback visualization\")\n",
            "    india_geojson = None\n",
            "\n",
            "if india_geojson:\n",
            "    # Prepare data for choropleth\n",
            "    choropleth_data = state_df[['state', 'ifi', 'total_enrolments', 'composite']].copy()\n",
            "    \n",
            "    # State name mapping for GeoJSON compatibility\n",
            "    geojson_name_map = {\n",
            "        'Andaman And Nicobar Islands': 'Andaman & Nicobar Island',\n",
            "        'Dadra And Nagar Haveli And Daman And Diu': 'Dadara & Nagar Havelli',\n",
            "        'Jammu And Kashmir': 'Jammu & Kashmir',\n",
            "        'Delhi': 'NCT of Delhi'\n",
            "    }\n",
            "    \n",
            "    choropleth_data['state_geojson'] = choropleth_data['state'].replace(geojson_name_map)\n",
            "    \n",
            "    # Create choropleth\n",
            "    fig = px.choropleth(\n",
            "        choropleth_data,\n",
            "        geojson=india_geojson,\n",
            "        locations='state_geojson',\n",
            "        featureidkey='properties.ST_NM',\n",
            "        color='ifi',\n",
            "        color_continuous_scale='RdYlGn',\n",
            "        range_color=[0, choropleth_data['ifi'].quantile(0.9)],\n",
            "        hover_name='state',\n",
            "        hover_data={'ifi': ':.1f', 'total_enrolments': ':,.0f', 'state_geojson': False},\n",
            "        labels={'ifi': 'IFI Score'},\n",
            "        title='<b>India Identity Freshness Index (IFI) Map</b><br><sup>Green = Healthy Data | Red = Staleness Risk</sup>'\n",
            "    )\n",
            "    \n",
            "    fig.update_geos(\n",
            "        visible=False,\n",
            "        fitbounds='locations',\n",
            "        bgcolor='white'\n",
            "    )\n",
            "    \n",
            "    fig.update_layout(\n",
            "        margin={'r': 0, 't': 60, 'l': 0, 'b': 0},\n",
            "        paper_bgcolor='white',\n",
            "        font=dict(family='Arial', size=12),\n",
            "        coloraxis_colorbar=dict(\n",
            "            title='IFI Score',\n",
            "            tickvals=[0, 10, 20, 30, 40],\n",
            "            ticktext=['Critical', '10', '20', '30', 'Healthy']\n",
            "        )\n",
            "    )\n",
            "    \n",
            "    # Save as static image\n",
            "    fig.write_image('../visualizations/india_choropleth_ifi.png', width=1200, height=800, scale=2)\n",
            "    print(\"✓ Choropleth saved to: visualizations/india_choropleth_ifi.png\")\n",
            "    \n",
            "    # Display\n",
            "    fig.show()\n",
            "else:\n",
            "    print(\"Creating alternative geographic visualization...\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# ALTERNATIVE: STATIC CHOROPLETH-STYLE MAP\n",
            "# ============================================\n",
            "\n",
            "# Create a visually impactful heatmap-style representation\n",
            "fig, ax = plt.subplots(figsize=(16, 12))\n",
            "\n",
            "# Prepare data sorted by region and IFI\n",
            "map_data = state_df.sort_values('ifi').copy()\n",
            "\n",
            "# Create a grid-like visualization resembling a map\n",
            "n_states = len(map_data)\n",
            "n_cols = 6\n",
            "n_rows = (n_states + n_cols - 1) // n_cols\n",
            "\n",
            "# Create color array based on IFI\n",
            "ifi_norm = (map_data['ifi'] - map_data['ifi'].min()) / (map_data['ifi'].max() - map_data['ifi'].min())\n",
            "colors = plt.cm.RdYlGn(ifi_norm)\n",
            "\n",
            "# Plot as a treemap-style grid\n",
            "for idx, (_, row) in enumerate(map_data.iterrows()):\n",
            "    col = idx % n_cols\n",
            "    row_pos = idx // n_cols\n",
            "    \n",
            "    # Size based on enrolment\n",
            "    size = 0.3 + (row['total_enrolments'] / map_data['total_enrolments'].max()) * 0.6\n",
            "    \n",
            "    # Color based on IFI\n",
            "    color_idx = (row['ifi'] - map_data['ifi'].min()) / (map_data['ifi'].max() - map_data['ifi'].min())\n",
            "    color = plt.cm.RdYlGn(color_idx)\n",
            "    \n",
            "    # Draw rectangle\n",
            "    rect = plt.Rectangle((col, n_rows - row_pos - 1), size, size, \n",
            "                         facecolor=color, edgecolor='white', linewidth=2)\n",
            "    ax.add_patch(rect)\n",
            "    \n",
            "    # Add state name\n",
            "    state_short = row['state'][:12] + '...' if len(row['state']) > 12 else row['state']\n",
            "    ax.text(col + size/2, n_rows - row_pos - 1 + size/2, \n",
            "            f\"{state_short}\\nIFI:{row['ifi']:.0f}\",\n",
            "            ha='center', va='center', fontsize=7, fontweight='bold',\n",
            "            color='white' if color_idx < 0.5 else 'black')\n",
            "\n",
            "ax.set_xlim(-0.5, n_cols + 0.5)\n",
            "ax.set_ylim(-0.5, n_rows + 0.5)\n",
            "ax.set_aspect('equal')\n",
            "ax.axis('off')\n",
            "\n",
            "# Add title\n",
            "ax.set_title('India State IFI Map\\n(Size = Enrolment Volume, Color = IFI Score)', \n",
            "             fontsize=18, fontweight='bold', pad=20)\n",
            "\n",
            "# Add colorbar\n",
            "sm = plt.cm.ScalarMappable(cmap='RdYlGn', norm=plt.Normalize(vmin=map_data['ifi'].min(), vmax=map_data['ifi'].max()))\n",
            "sm.set_array([])\n",
            "cbar = plt.colorbar(sm, ax=ax, shrink=0.6, aspect=20)\n",
            "cbar.set_label('IFI Score (Higher = Better)', fontsize=12)\n",
            "\n",
            "# Add legend\n",
            "ax.text(0.02, 0.02, '🔴 Red = Critical (Low IFI)\\n🟢 Green = Healthy (High IFI)', \n",
            "        transform=ax.transAxes, fontsize=10, verticalalignment='bottom',\n",
            "        bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('../visualizations/india_state_map_grid.png', dpi=300, bbox_inches='tight', facecolor='white')\n",
            "plt.show()\n",
            "\n",
            "print(\"\\n✅ State map grid saved to: visualizations/india_state_map_grid.png\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# GEOGRAPHIC RISK SUMMARY\n",
            "# ============================================\n",
            "\n",
            "print(\"\\n\" + \"=\"*70)\n",
            "print(\"📊 GEOGRAPHIC RISK SUMMARY\")\n",
            "print(\"=\"*70)\n",
            "\n",
            "# Critical states\n",
            "critical_states = state_df[state_df['ifi'] < 10].sort_values('ifi')\n",
            "print(f\"\\n🔴 CRITICAL ZONES (IFI < 10): {len(critical_states)} states\")\n",
            "for _, row in critical_states.head(5).iterrows():\n",
            "    print(f\"   • {row['state']}: IFI = {row['ifi']:.1f}\")\n",
            "\n",
            "# At-risk states\n",
            "at_risk_states = state_df[(state_df['ifi'] >= 10) & (state_df['ifi'] < 20)]\n",
            "print(f\"\\n🟡 AT-RISK ZONES (IFI 10-20): {len(at_risk_states)} states\")\n",
            "\n",
            "# Healthy states\n",
            "healthy_states = state_df[state_df['ifi'] >= 20]\n",
            "print(f\"\\n🟢 HEALTHY ZONES (IFI >= 20): {len(healthy_states)} states\")\n",
            "\n",
            "# Population at risk\n",
            "if 'population_2024_est' in state_df.columns:\n",
            "    pop_at_risk = state_df[state_df['ifi'] < 15]['population_2024_est'].sum()\n",
            "    print(f\"\\n👥 ESTIMATED POPULATION AT RISK: {pop_at_risk/1e6:.0f} Million\")\n",
            "\n",
            "print(\"\\n\" + \"=\"*70)"
        ]
    }
]

# Add choropleth cells to notebook
nb['cells'].extend(choropleth_cells)

# Save updated notebook
with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=4)

print(f"✅ Choropleth map section added!")
print(f"   Total cells now: {len(nb['cells'])}")
print("\nNew features:")
print("   • Interactive Plotly choropleth (if GeoJSON loads)")
print("   • Static grid-style state map (fallback)")
print("   • Geographic risk summary")
