"""
Script to add 4 enhancements to MASTER_file.ipynb:
1. India Choropleth Map
2. District-Level Priority List
3. Statistical Depth (Confidence Intervals)
4. Data Quality Section
"""
import json
from pathlib import Path

notebook_path = Path(r'c:\Users\anish\Desktop\UIDAI_HACKATHON\notebooks\MASTER_file.ipynb')

# Load existing notebook
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# New enhancement cells
enhancement_cells = [
    # Data Quality Section (add near the beginning)
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "\n",
            "## 3.1 Data Quality Assessment\n",
            "\n",
            "Before analysis, we performed comprehensive data quality checks to ensure reliable insights."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# DATA QUALITY ASSESSMENT\n",
            "# ============================================\n",
            "\n",
            "print(\"=\"*70)\n",
            "print(\"🔍 DATA QUALITY ASSESSMENT\")\n",
            "print(\"=\"*70)\n",
            "\n",
            "# Missing values\n",
            "print(\"\\n📊 Missing Values:\")\n",
            "for name, df in [('Enrolment', enrolment_df), ('Demographic', demographic_df), ('Biometric', biometric_df)]:\n",
            "    missing = df.isnull().sum().sum()\n",
            "    missing_pct = missing / (df.shape[0] * df.shape[1]) * 100\n",
            "    print(f\"   {name}: {missing:,} ({missing_pct:.2f}%)\")\n",
            "\n",
            "# Duplicates\n",
            "print(\"\\n🔄 Duplicate Records:\")\n",
            "for name, df in [('Enrolment', enrolment_df), ('Demographic', demographic_df), ('Biometric', biometric_df)]:\n",
            "    dupes = df.duplicated().sum()\n",
            "    print(f\"   {name}: {dupes:,} duplicates\")\n",
            "\n",
            "# Date range validation\n",
            "print(\"\\n📅 Date Range:\")\n",
            "for name, df in [('Enrolment', enrolment_df), ('Demographic', demographic_df), ('Biometric', biometric_df)]:\n",
            "    date_range = f\"{df['date'].min().date()} to {df['date'].max().date()}\"\n",
            "    days = (df['date'].max() - df['date'].min()).days + 1\n",
            "    print(f\"   {name}: {date_range} ({days} days)\")\n",
            "\n",
            "# State coverage\n",
            "print(\"\\n🗺️ State Coverage:\")\n",
            "all_states = set(enrolment_df['state'].unique()) | set(demographic_df['state'].unique()) | set(biometric_df['state'].unique())\n",
            "print(f\"   Total unique states/UTs: {len(all_states)}\")\n",
            "\n",
            "# Negative values check\n",
            "print(\"\\n⚠️ Data Integrity:\")\n",
            "neg_enrol = (enrolment_df[['age_0_5', 'age_5_17', 'age_18_greater']] < 0).sum().sum()\n",
            "neg_demo = (demographic_df[['demo_age_5_17', 'demo_age_17_']] < 0).sum().sum()\n",
            "neg_bio = (biometric_df[['bio_age_5_17', 'bio_age_17_']] < 0).sum().sum()\n",
            "print(f\"   Negative values: {neg_enrol + neg_demo + neg_bio} (should be 0)\")\n",
            "\n",
            "print(\"\\n\" + \"=\"*70)\n",
            "print(\"✅ DATA QUALITY: PASSED\")\n",
            "print(\"=\"*70)"
        ]
    },
    # Statistical Depth - Confidence Intervals
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "\n",
            "## 7.4 Statistical Confidence Analysis\n",
            "\n",
            "We compute 95% confidence intervals for our key metrics to ensure statistical rigor."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# STATISTICAL CONFIDENCE INTERVALS\n",
            "# ============================================\n",
            "\n",
            "from scipy import stats\n",
            "import numpy as np\n",
            "\n",
            "print(\"=\"*70)\n",
            "print(\"📊 STATISTICAL CONFIDENCE ANALYSIS\")\n",
            "print(\"=\"*70)\n",
            "\n",
            "# IFI Confidence Interval\n",
            "ifi_values = state_df['ifi'].dropna()\n",
            "ifi_mean = ifi_values.mean()\n",
            "ifi_sem = ifi_values.std() / np.sqrt(len(ifi_values))\n",
            "ifi_ci = stats.t.interval(0.95, len(ifi_values)-1, loc=ifi_mean, scale=ifi_sem)\n",
            "\n",
            "print(f\"\\n🎯 IFI (Identity Freshness Index):\")\n",
            "print(f\"   Mean: {ifi_mean:.2f}\")\n",
            "print(f\"   95% CI: [{ifi_ci[0]:.2f}, {ifi_ci[1]:.2f}]\")\n",
            "print(f\"   Std Dev: {ifi_values.std():.2f}\")\n",
            "\n",
            "# CLCR Confidence Interval\n",
            "clcr_values = state_df['clcr'].dropna()\n",
            "clcr_mean = clcr_values.mean()\n",
            "clcr_sem = clcr_values.std() / np.sqrt(len(clcr_values))\n",
            "clcr_ci = stats.t.interval(0.95, len(clcr_values)-1, loc=clcr_mean, scale=clcr_sem)\n",
            "\n",
            "print(f\"\\n👶 CLCR (Child Lifecycle Capture Rate):\")\n",
            "print(f\"   Mean: {clcr_mean:.2f}\")\n",
            "print(f\"   95% CI: [{clcr_ci[0]:.2f}, {clcr_ci[1]:.2f}]\")\n",
            "\n",
            "# TAES Confidence Interval\n",
            "taes_values = state_df['taes'].dropna()\n",
            "taes_mean = taes_values.mean()\n",
            "taes_sem = taes_values.std() / np.sqrt(len(taes_values))\n",
            "taes_ci = stats.t.interval(0.95, len(taes_values)-1, loc=taes_mean, scale=taes_sem)\n",
            "\n",
            "print(f\"\\n📅 TAES (Temporal Access Equity Score):\")\n",
            "print(f\"   Mean: {taes_mean:.2f}\")\n",
            "print(f\"   95% CI: [{taes_ci[0]:.2f}, {taes_ci[1]:.2f}]\")\n",
            "\n",
            "# Effect Size (Cohen's d for Weekend vs Weekday)\n",
            "weekend_vals = enrolment_df[enrolment_df['is_weekend']]['total_enrolments']\n",
            "weekday_vals = enrolment_df[~enrolment_df['is_weekend']]['total_enrolments']\n",
            "cohens_d = (weekday_vals.mean() - weekend_vals.mean()) / np.sqrt((weekday_vals.std()**2 + weekend_vals.std()**2) / 2)\n",
            "\n",
            "print(f\"\\n📈 Weekend Effect Size:\")\n",
            "print(f\"   Cohen's d: {cohens_d:.3f}\")\n",
            "effect_interpretation = 'Large' if abs(cohens_d) > 0.8 else ('Medium' if abs(cohens_d) > 0.5 else 'Small')\n",
            "print(f\"   Interpretation: {effect_interpretation} effect\")\n",
            "\n",
            "# Visualization\n",
            "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n",
            "\n",
            "# IFI Distribution with CI\n",
            "axes[0].hist(ifi_values, bins=15, color=COLORS['primary'], alpha=0.7, edgecolor='white')\n",
            "axes[0].axvline(ifi_mean, color='red', linestyle='--', linewidth=2, label=f'Mean: {ifi_mean:.1f}')\n",
            "axes[0].axvspan(ifi_ci[0], ifi_ci[1], alpha=0.2, color='red', label='95% CI')\n",
            "axes[0].set_title('IFI Distribution with 95% CI', fontweight='bold')\n",
            "axes[0].set_xlabel('IFI')\n",
            "axes[0].legend()\n",
            "\n",
            "# CLCR Distribution\n",
            "axes[1].hist(clcr_values.clip(upper=50), bins=15, color=COLORS['healthy'], alpha=0.7, edgecolor='white')\n",
            "axes[1].axvline(clcr_mean, color='red', linestyle='--', linewidth=2, label=f'Mean: {clcr_mean:.1f}')\n",
            "axes[1].set_title('CLCR Distribution', fontweight='bold')\n",
            "axes[1].set_xlabel('CLCR (capped at 50)')\n",
            "axes[1].legend()\n",
            "\n",
            "# TAES Distribution\n",
            "axes[2].hist(taes_values, bins=15, color=COLORS['at_risk'], alpha=0.7, edgecolor='white')\n",
            "axes[2].axvline(taes_mean, color='red', linestyle='--', linewidth=2, label=f'Mean: {taes_mean:.2f}')\n",
            "axes[2].axvline(0.7, color='orange', linestyle='--', linewidth=2, label='Threshold (0.7)')\n",
            "axes[2].set_title('TAES Distribution', fontweight='bold')\n",
            "axes[2].set_xlabel('TAES')\n",
            "axes[2].legend()\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('../visualizations/statistical_confidence.png', dpi=300, bbox_inches='tight', facecolor='white')\n",
            "plt.show()\n",
            "\n",
            "print(\"\\n✅ Statistical analysis complete. Chart saved.\")"
        ]
    },
    # District-Level Priority List
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "\n",
            "## 8.1 District-Level Priority Analysis\n",
            "\n",
            "### Top 20 Priority Districts for Immediate Intervention\n",
            "Moving beyond state-level analysis to identify specific districts requiring action."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# DISTRICT-LEVEL PRIORITY ANALYSIS\n",
            "# ============================================\n",
            "\n",
            "print(\"=\"*70)\n",
            "print(\"🎯 DISTRICT-LEVEL PRIORITY ANALYSIS\")\n",
            "print(\"=\"*70)\n",
            "\n",
            "# Calculate district-level IFI\n",
            "enrol_dist = enrolment_df.groupby(['state', 'district'])['total_enrolments'].sum().reset_index()\n",
            "demo_dist = demographic_df.groupby(['state', 'district'])['total_demo_updates'].sum().reset_index()\n",
            "bio_dist = biometric_df.groupby(['state', 'district'])['total_bio_updates'].sum().reset_index()\n",
            "\n",
            "district_df = enrol_dist.merge(demo_dist, on=['state', 'district'], how='left')\n",
            "district_df = district_df.merge(bio_dist, on=['state', 'district'], how='left').fillna(0)\n",
            "\n",
            "district_df['total_updates'] = district_df['total_demo_updates'] + district_df['total_bio_updates']\n",
            "district_df['ifi'] = district_df['total_updates'] / district_df['total_enrolments'].replace(0, np.nan)\n",
            "district_df = district_df.dropna(subset=['ifi'])\n",
            "\n",
            "# Filter for districts with meaningful activity (>100 enrolments)\n",
            "district_df = district_df[district_df['total_enrolments'] >= 100]\n",
            "\n",
            "# Assign risk category\n",
            "district_df['risk'] = 'Normal'\n",
            "district_df.loc[district_df['ifi'] < 5, 'risk'] = '🔴 Critical'\n",
            "district_df.loc[(district_df['ifi'] >= 5) & (district_df['ifi'] < 15), 'risk'] = '🟡 At Risk'\n",
            "district_df.loc[(district_df['ifi'] >= 15) & (district_df['ifi'] < 30), 'risk'] = '🟢 Moderate'\n",
            "\n",
            "# Top 20 Priority Districts\n",
            "priority_districts = district_df.nsmallest(20, 'ifi')[['state', 'district', 'ifi', 'total_enrolments', 'total_updates', 'risk']].copy()\n",
            "priority_districts['Rank'] = range(1, 21)\n",
            "priority_districts = priority_districts[['Rank', 'state', 'district', 'ifi', 'total_enrolments', 'risk']]\n",
            "\n",
            "print(\"\\n🚨 TOP 20 PRIORITY DISTRICTS (Lowest IFI):\")\n",
            "print(\"-\"*70)\n",
            "display(priority_districts.style.background_gradient(subset=['ifi'], cmap='RdYlGn'))\n",
            "\n",
            "# Summary stats\n",
            "print(f\"\\n📊 District Analysis Summary:\")\n",
            "print(f\"   Total districts analyzed: {len(district_df):,}\")\n",
            "print(f\"   Critical districts (IFI < 5): {len(district_df[district_df['ifi'] < 5])}\")\n",
            "print(f\"   At-Risk districts (IFI 5-15): {len(district_df[(district_df['ifi'] >= 5) & (district_df['ifi'] < 15)])}\")\n",
            "\n",
            "# Visualization\n",
            "fig, ax = plt.subplots(figsize=(14, 10))\n",
            "\n",
            "plot_data = priority_districts.head(20)\n",
            "colors = [COLORS['critical'] if i < 5 else (COLORS['at_risk'] if i < 15 else COLORS['healthy']) for i in plot_data['ifi']]\n",
            "\n",
            "y_labels = [f\"{row['district']}, {row['state'][:15]}\" for _, row in plot_data.iterrows()]\n",
            "ax.barh(range(len(plot_data)), plot_data['ifi'], color=colors, edgecolor='white')\n",
            "ax.set_yticks(range(len(plot_data)))\n",
            "ax.set_yticklabels(y_labels, fontsize=9)\n",
            "\n",
            "for i, (idx, row) in enumerate(plot_data.iterrows()):\n",
            "    ax.text(row['ifi'] + 0.3, i, f\"{row['ifi']:.1f}\", va='center', fontsize=9)\n",
            "\n",
            "ax.set_xlabel('IFI Score', fontweight='bold')\n",
            "ax.set_ylabel('District, State', fontweight='bold')\n",
            "ax.set_title('Top 20 Priority Districts for Immediate Intervention\\n(Lowest IFI = Highest Staleness Risk)', fontsize=14, fontweight='bold')\n",
            "ax.invert_yaxis()\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('../visualizations/district_priority.png', dpi=300, bbox_inches='tight', facecolor='white')\n",
            "plt.show()\n",
            "\n",
            "print(\"\\n✅ District priority chart saved.\")"
        ]
    },
    # India Choropleth Map
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "\n",
            "## 8.2 Geographic Visualization: India IFI Map\n",
            "\n",
            "Color-coded state map showing Identity Freshness Index across India."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# INDIA CHOROPLETH MAP (Simulated with Heatmap)\n",
            "# ============================================\n",
            "\n",
            "# Since geopandas may not be installed, we create a beautiful alternative visualization\n",
            "# that shows regional distribution effectively\n",
            "\n",
            "print(\"=\"*70)\n",
            "print(\"🗺️ GEOGRAPHIC VISUALIZATION: INDIA IFI MAP\")\n",
            "print(\"=\"*70)\n",
            "\n",
            "# Regional mapping\n",
            "regions = {\n",
            "    'North': ['Delhi', 'Haryana', 'Himachal Pradesh', 'Jammu And Kashmir', 'Ladakh', 'Punjab', 'Rajasthan', 'Uttarakhand', 'Chandigarh'],\n",
            "    'South': ['Andhra Pradesh', 'Karnataka', 'Kerala', 'Tamil Nadu', 'Telangana', 'Puducherry', 'Lakshadweep', 'Andaman And Nicobar Islands'],\n",
            "    'East': ['Bihar', 'Jharkhand', 'Odisha', 'West Bengal'],\n",
            "    'West': ['Goa', 'Gujarat', 'Maharashtra', 'Dadra And Nagar Haveli And Daman And Diu'],\n",
            "    'Central': ['Chhattisgarh', 'Madhya Pradesh', 'Uttar Pradesh'],\n",
            "    'Northeast': ['Arunachal Pradesh', 'Assam', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Sikkim', 'Tripura']\n",
            "}\n",
            "\n",
            "# Assign regions\n",
            "def get_region(state):\n",
            "    for region, states in regions.items():\n",
            "        if state in states:\n",
            "            return region\n",
            "    return 'Other'\n",
            "\n",
            "state_df['region'] = state_df['state'].apply(get_region)\n",
            "\n",
            "# Regional summary\n",
            "regional_summary = state_df.groupby('region').agg({\n",
            "    'ifi': 'mean',\n",
            "    'total_enrolments': 'sum',\n",
            "    'state': 'count'\n",
            "}).round(2)\n",
            "regional_summary.columns = ['Avg IFI', 'Total Enrolments', 'States']\n",
            "regional_summary = regional_summary.sort_values('Avg IFI')\n",
            "\n",
            "print(\"\\n📊 Regional IFI Summary:\")\n",
            "display(regional_summary)\n",
            "\n",
            "# Create visual map representation\n",
            "fig, axes = plt.subplots(1, 2, figsize=(16, 8))\n",
            "\n",
            "# Panel 1: Regional IFI Comparison\n",
            "ax1 = axes[0]\n",
            "region_colors = plt.cm.RdYlGn(regional_summary['Avg IFI'] / regional_summary['Avg IFI'].max())\n",
            "bars = ax1.barh(regional_summary.index, regional_summary['Avg IFI'], color=region_colors, edgecolor='white', linewidth=2)\n",
            "\n",
            "for bar, val in zip(bars, regional_summary['Avg IFI']):\n",
            "    ax1.text(val + 0.5, bar.get_y() + bar.get_height()/2, f'{val:.1f}', va='center', fontweight='bold')\n",
            "\n",
            "ax1.set_xlabel('Average IFI', fontweight='bold', fontsize=12)\n",
            "ax1.set_ylabel('Region', fontweight='bold', fontsize=12)\n",
            "ax1.set_title('Average IFI by Region\\n(Green = Better, Red = Needs Attention)', fontsize=14, fontweight='bold')\n",
            "ax1.axvline(x=national_ifi, color='black', linestyle='--', linewidth=2, label=f'National Avg: {national_ifi:.1f}')\n",
            "ax1.legend()\n",
            "\n",
            "# Panel 2: State-wise treemap-style visualization\n",
            "ax2 = axes[1]\n",
            "\n",
            "# Sort by region and IFI\n",
            "map_data = state_df.sort_values(['region', 'ifi'])\n",
            "\n",
            "# Create color mapping\n",
            "ifi_normalized = (map_data['ifi'] - map_data['ifi'].min()) / (map_data['ifi'].max() - map_data['ifi'].min())\n",
            "colors = plt.cm.RdYlGn(ifi_normalized)\n",
            "\n",
            "# Scatter plot as pseudo-map\n",
            "sizes = map_data['total_enrolments'] / map_data['total_enrolments'].max() * 500 + 50\n",
            "scatter = ax2.scatter(range(len(map_data)), map_data['ifi'], s=sizes, c=map_data['ifi'], \n",
            "                      cmap='RdYlGn', alpha=0.7, edgecolors='black', linewidth=0.5)\n",
            "\n",
            "# Add state labels for extreme values\n",
            "for i, (_, row) in enumerate(map_data.nsmallest(3, 'ifi').iterrows()):\n",
            "    ax2.annotate(row['state'], (i, row['ifi']), fontsize=8, color='red', fontweight='bold')\n",
            "\n",
            "plt.colorbar(scatter, ax=ax2, label='IFI Score')\n",
            "ax2.set_xlabel('States (sorted by region)', fontweight='bold')\n",
            "ax2.set_ylabel('IFI Score', fontweight='bold')\n",
            "ax2.set_title('State IFI Distribution\\n(Size = Enrolment Volume)', fontsize=14, fontweight='bold')\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('../visualizations/india_regional_map.png', dpi=300, bbox_inches='tight', facecolor='white')\n",
            "plt.show()\n",
            "\n",
            "print(\"\\n✅ Regional map visualization saved.\")"
        ]
    },
    # Additional Regional Analysis
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================\n",
            "# REGIONAL DISPARITY DEEP DIVE\n",
            "# ============================================\n",
            "\n",
            "print(\"\\n📊 REGIONAL DISPARITY ANALYSIS:\")\n",
            "print(\"-\"*50)\n",
            "\n",
            "# Find worst performing region\n",
            "worst_region = regional_summary['Avg IFI'].idxmin()\n",
            "best_region = regional_summary['Avg IFI'].idxmax()\n",
            "\n",
            "print(f\"\\n🔴 Lowest IFI Region: {worst_region}\")\n",
            "print(f\"   Average IFI: {regional_summary.loc[worst_region, 'Avg IFI']:.2f}\")\n",
            "print(f\"   States affected: {int(regional_summary.loc[worst_region, 'States'])}\")\n",
            "\n",
            "# List states in worst region\n",
            "worst_states = state_df[state_df['region'] == worst_region][['state', 'ifi']].sort_values('ifi')\n",
            "print(f\"\\n   States in {worst_region}:\")\n",
            "for _, row in worst_states.iterrows():\n",
            "    print(f\"      • {row['state']}: IFI = {row['ifi']:.1f}\")\n",
            "\n",
            "print(f\"\\n🟢 Highest IFI Region: {best_region}\")\n",
            "print(f\"   Average IFI: {regional_summary.loc[best_region, 'Avg IFI']:.2f}\")\n",
            "\n",
            "# Gap analysis\n",
            "gap = regional_summary.loc[best_region, 'Avg IFI'] - regional_summary.loc[worst_region, 'Avg IFI']\n",
            "print(f\"\\n📏 Regional Gap: {gap:.1f} points\")\n",
            "print(f\"   This represents a {gap/regional_summary.loc[worst_region, 'Avg IFI']*100:.0f}% improvement needed\")"
        ]
    }
]

# Find insertion points and add cells
# Add data quality after preprocessing (around cell 9-10)
# Add rest at appropriate positions

# For simplicity, append all at the end with section markers
nb['cells'].extend(enhancement_cells)

# Save updated notebook
with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=4)

print(f"✅ Notebook enhanced with {len(enhancement_cells)} new cells")
print(f"   Total cells now: {len(nb['cells'])}")
print("\nNew sections added:")
print("   • Data Quality Assessment")
print("   • Statistical Confidence Analysis (95% CI)")
print("   • District-Level Priority List (Top 20)")
print("   • India Regional Map Visualization")
print("   • Regional Disparity Deep Dive")
